language: 
- python
- java
- generic
- ruby
matrix:
    include:
        - os: linux
          sudo: required
          python: 2.7 
          env: TOXENV=py27 DISPLAY=':0.0' 
          install:
          - pip install -U selenium
          - pip install -U pyvirtualdisplay
          - pip install -U sauceclient
          - pip install -r python/requirements.txt
          script:
          - export DISPLAY=:0.0;cd python;python applitools_sauce_test.py
        - os: linux
          sudo: required
          python: 3.3
          env: TOXENV=py33 DISPLAY=':0.0'  
          install:
          - pip install -U selenium
          - pip install -U pyvirtualdisplay
          - pip install -U sauceclient
          - pip install -r python/requirements.txt
          script:
          - export DISPLAY=:0.0;cd python;python applitools_sauce_test.py
        - os: osx
          language: generic
          env: TOXENV=py27 DISPLAY=':0.0'  
          install:
          - pip install -U selenium
          - pip install -U pyvirtualdisplay
          - pip install -U sauceclient
          - pip install -r python/requirements.txt
          script:
          - export DISPLAY=:0.0;cd python;python applitools_sauce_test.py
        - os: osx
          language: generic
          env: TOXENV=py33 DISPLAY=':0.0'  
          install:
          - pip install -U selenium
          - pip install -U pyvirtualdisplay
          - pip install -U sauceclient
          - pip install -r python/requirements.txt
          script:
          - export DISPLAY=:0.0;cd python;python applitools_sauce_test.py
        - os: linux
          language: java
          jdk: oraclejdk8
          env: DISPLAY=':0.0'   
          install: cd java/sdk/eyes.selenium.java/;mvn test
        - os: osx
          language: java
          osx_image: xcode8
          env: DISPLAY=':0.0'  
          install: cd java/sdk/eyes.selenium.java/;mvn test
        - os : linux 
          language: ruby
          sudo: required
          env: DISPLAY=':0.0'  
          ruby:
          #- 1.9.3
          - 2.0.0
          #- 2.1.6
          #- 2.3.1
          #- rbx-2
          matrix:
            allow_failures:
            - rvm: rbx-2
          before_install:
          - "export DISPLAY=:99.0"
          - "sh -e /etc/init.d/xvfb start"
          - wget -N http://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip -P ~/
          - unzip ~/chromedriver_linux64.zip -d ~/
          - chmod +x ~/chromedriver
          - sudo mv -f ~/chromedriver /usr/local/share/chromedriver
          - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
          - sudo ln -s /usr/local/share/chromedriver /usr/bin/google-chrome
          - rvm reinstall ruby-head --binary
          - gem install public_suffix -v '2.0.5'
          - cd ruby/sdk/ext/eyes_core;ruby extconf.rb;make;make install
          script:
          - cd ../.. 
          - bundle install
          - bundle exec rake rubocop
          - bundle exec rspec examples/check_frame_and_element_example.rb
