language: 
- python
- java
- generic
- ruby
matrix:
    include:
        - os: linux
          sudo: required
          python: 2.7 
          env: TOXENV=py27 DISPLAY=':0.0' 
          install:
          - pip install -U selenium
          - pip install -U pyvirtualdisplay
          - pip install -U sauceclient
          - pip install -r python/requirements.txt
          script:
          - export DISPLAY=:0.0;cd python;python applitools_sauce_test.py
        - os: linux
          sudo: required
          python: 3.3
          env: TOXENV=py33 DISPLAY=':0.0'  
          install:
          - pip install -U selenium
          - pip install -U pyvirtualdisplay
          - pip install -U sauceclient
          - pip install -r python/requirements.txt
          script:
          - export DISPLAY=:0.0;cd python;python applitools_sauce_test.py
        - os: osx
          language: generic
          env: TOXENV=py27 DISPLAY=':0.0'  
          install:
          - pip install -U selenium
          - pip install -U pyvirtualdisplay
          - pip install -U sauceclient
          - pip install -r python/requirements.txt
          script:
          - export DISPLAY=:0.0;cd python;python applitools_sauce_test.py
        - os: osx
          language: generic
          env: TOXENV=py33 DISPLAY=':0.0'  
          install:
          - pip install -U selenium
          - pip install -U pyvirtualdisplay
          - pip install -U sauceclient
          - pip install -r python/requirements.txt
          script:
          - export DISPLAY=:0.0;cd python;python applitools_sauce_test.py
        - os: linux
          language: java
          jdk: oraclejdk8
          env: DISPLAY=':0.0'   
          install: cd java/sdk/eyes.selenium.java/;mvn test
        - os: osx
          language: java
          osx_image: xcode8
          env: DISPLAY=':0.0'  
          install: cd java/sdk/eyes.selenium.java/;mvn test
        - os : linux 
          language: ruby
          rvm: 2.3.4
          sudo: required
          env: DISPLAY=':0.0'  
          dist: trusty
          before_install:
          #- wget -N http://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip -P ~/
          #- unzip ~/chromedriver_linux64.zip -d ~/
          #- chmod +x ~/chromedriver
          #- sudo mv -f ~/chromedriver /usr/local/share/chromedriver
          #- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
          - rvm reinstall ruby-head --binary
          - gem install public_suffix -v '2.0.5'
          - cd ruby; bundle install 
          - cd sdk/ext/eyes_core;ruby extconf.rb;make;make install
          script:
          - cd ../.. 
          - bundle install --quiet 
          - bundle exec rake rubocop
          - cd examples
          #- bundle exec rspec check_frame_and_element_example.rb
          #- bundle exec rspec check_frame_and_element_fluent_interface_example.rb
          #- bundle exec rspec images_example_fluent_interface_script.rb
          #- bundle exec rspec images_example_script.rb
          #- bundle exec rspec images_single_example_fi_script.rb
          - bundle exec rspec sauce_capybara_example.rb
          ##- bundle exec rspec watir_test_script.rb
        - os : linux 
          language: ruby
          sudo: required
          env: DISPLAY=':0.0'
          dist: trusty
          rvm: ruby-1.9.3-p551
          before_install:
          #- curl https://chromedriver.storage.googleapis.com/2.31/chromedriver_mac64.zip -o /tmp/chromedriver_mac64.zip 
          #- unzip /tmp/chromedriver_mac64.zip -d /tmp
          #- chmod +x /tmp/chromedriver
          #- sudo mv -f /tmp/chromedriver /usr/local/share/chromedriver
          #- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
          - rvm install ruby-head --binary
          - gem install public_suffix -v '2.0.5'
          - cd ruby
          - bundle install 
          - cd sdk/ext/eyes_core;ruby extconf.rb;make;make install
          script:
          - cd ../..
          - bundle install --quiet
          - bundle exec rake rubocop
          - cd examples
          - bundle exec rspec check_frame_and_element_example.rb
          - bundle exec rspec check_frame_and_element_fluent_interface_example.rb
          - bundle exec rspec images_example_fluent_interface_script.rb
          - bundle exec rspec images_example_script.rb
          - bundle exec rspec images_single_example_fi_script.rb
          - bundle exec rspec capybara_example.rb
          - bundle exec rspec watir_test_script.rb
